# Generated by Django 4.1.3 on 2022-11-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField(verbose_name='Thumbnail')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('icon', models.URLField(verbose_name='Icon')),
            ],
        ),
    ]
