# Generated by Django 4.1.3 on 2022-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='star',
            field=models.BooleanField(default=False, verbose_name='Star'),
        ),
    ]
