# Generated by Django 4.1.3 on 2022-11-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.CharField(default='', max_length=300, verbose_name='Profile'),
            preserve_default=False,
        ),
    ]
