# Generated by Django 4.1.3 on 2022-11-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.CharField(max_length=30, verbose_name='Tags'),
        ),
    ]
