# Generated by Django 4.1.3 on 2022-11-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Seen'),
        ),
    ]
