# Generated by Django 4.1.3 on 2022-12-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_video_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.CharField(default=0.00016485328058028355, max_length=30, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
